backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
  - name: Homepage
    label: Inicio
    description: Contenido de la página de inicio
    create: false
    delete: false
    editor:
      preview: false
    files: 
      - file: src/content/homepage.json
        name: HomePage
        label: Activar Homepage
        description: Contenido de la sección HomePage
        fields:
          - name: name
            widget: hidden
            default: home-page
          - name: enabled
            widget: boolean
            default: true
            label: Home Page
          - name: text
            widget: string
            required: true
            label: Texto Homepage

  - name: Sections
    label: Secciones
    folder: src/content/sections
    description: Aca van tus secciones
    create: true
    delete: true
    fields:
      - name: name
        widget: hidden
        default: seccion
      - name: enabled
        widget: boolean
        default: true
        label: Activar
      - name: text
        widget: string
        required: true
        label: Texto Secciones
      - name: Featured Image
        media_folder: src/content/sections/thumbnails
        label: thumbnail
        widget: image
        media_library:
          config:
            multiple: true

  - name: Playlist
    label: playlist
    folder: src/content/playlist
    description: Aca van tus playlist
    create: true
    delete: true
    fields:
      - name: name
        widget: hidden
        default: playlist
      - name: enabled
        widget: boolean
        default: true
        label: Activar
      - name: text
        widget: string
        required: true
        label: Titulo de la playlist
      - name: text
        widget: string
        required: true
        label: Url de la playlist