backend:
  name: git-gateway
  media_folder: src/content/blog/images, 

collections:
  - name: settings
    label: Configuración
    create: false
    delete: false
    editor:
      preview: false
    files:
      - name: siteConfig
        file: src/content/settings/siteConfig.json
        label: Datos del sitio
        description: Datos generales del sitio
        fields:
          - name: siteTitle
            widget: string
            required: true
            label: Título del sitio
          - name: siteDescription
            widget: string
            required: true
            label: Descripción del sitio
          - name: author
            widget: string
            required: true
            label: Autor
          - name: contactEmail
            widget: string
            label: Email de contacto
            required: false
          - name: contactPhone
            widget: string
            label: Teléfono de contacto
            required: false
          - name: socialNetworks
            label: Redes Sociales
            widget: object
            fields:
              - name: facebook
                label: Facebook
                required: false
              - name: twitter
                label: Twitter
                required: false
              - name: instagram
                label: Instagram
                required: false
              - name: linkedin
                label: LinkedIn
                required: false
              - name: youtube
                label: YouTube
                required: false
              - name: twitch
                label: Twitch
                required: false
              - name: tumblr
                label: Tumblr
                required: false

  - name: Homepage
    label: Inicio
    description: Contenido de la página de inicio
    create: false
    delete: false
    editor:
      preview: false
    files: 
      - file: src/content/homepage.json
        name: HomePage
        label: Activar Homepage
        description: Contenido de la sección HomePage
        fields:
          - name: name
            widget: hidden
            default: home-page
          - name: enabled
            widget: boolean
            default: true
            label: Home Page
          - name: text
            widget: string
            required: true
            label: Texto Homepage

  - name: Sections
    label: Secciones
    folder: src/content/sections
    description: Aca van tus secciones
    create: true
    delete: true
    fields:
      - name: name
        widget: hidden
        default: seccion
      - name: enabled
        widget: boolean
        default: true
        label: Activar
      - name: text
        widget: string
        required: true
        label: Texto Secciones
      - name: Image
        media_folder: src/content/sections/thumbnails
        label: thumbnail
        widget: image
        media_library:
          config:
            multiple: true

  - name: playlist
    label: playlist
    folder: src/content/playlist
    description: Aca van tus playlist
    create: true
    delete: true
    fields:
      - name: name
        widget: hidden
        default: playlist
      - name: enabled
        widget: boolean
        default: true
        label: Activar
      - name: text
        widget: string
        required: true
        label: Titulo de la playlist
      - name: url
        widget: text
        required: true
        label: Url de la playlist
      - name: Image
        media_folder: src/content/playlist/thumbnails
        label: thumbnail
        widget: image
        media_library:
          config:
            multiple: true

  - name: Blog
    label: Blog
    folder: src/content/blog
    description: Aca van tus posts
    create: true
    delete: true
    fields:
      - { name: contentType, label: Content Type, widget: hidden, default: blog-post,}
      - { name: enabled, label: Publicado, widget: boolean, default: true }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title, required: true }
      - { name: image, label: Imagen, required: true, widget: image, 
          media_folder: src/content/blog/images, 
          media_library: { 
            config: { 
              multiple: false 
            }
          }
        }
      - { name: description, label: Description, widget: text, required: true }
      - { name: body, label: Body, widget: markdown, required: true }
      - { name: category, label: Categoria, widget: select, multiple: true, options: ["Libros", "Cine/Series", "Música", "Fotografía", "Juegos", "Destacados"]}
      - { name: author, label: Autor }